module SF::Graphics
  class RectangleShape < Shape
    def initialize: (?(SF::System::Vector2 | Array[Float]) size) -> void
    def self.[]: (Float left, Float top, Float width, Float height) -> RectangleShape

    def copy: () -> RectangleShape
    def move: (SF::System::Vector2 | Array[Float] offset) -> self
    def rotate: (Float angle) -> self
    def scale!: (SF::System::Vector2 | Array[Float] factors) -> self
    def draw: (untyped target, RenderState state) -> nil

    def size: () -> SF::System::Vector2
    def size=: (SF::System::Vector2 | Array[Float] value) -> SF::System::Vector2
    def position: () -> SF::System::Vector2
    def position=: (SF::System::Vector2 | Array[Float] value) -> SF::System::Vector2
    def rotation: () -> Float
    def rotation=: (Float value) -> Float
    def scale: () -> SF::System::Vector2
    def scale=: (SF::System::Vector2 | Array[Float] value) -> SF::System::Vector2
    def origin: () -> SF::System::Vector2
    def origin=: (SF::System::Vector2 | Array[Float] value) -> SF::System::Vector2
    def fill_color: () -> Color
    def fill_color=: (Color value) -> Color
    def outline_color: () -> Color
    def outline_color=: (Color value) -> Color
    def outline_thickness: () -> Float
    def outline_thickness=: (Float value) -> Float
    def texture: () -> (Texture | nil)
    def texture=: (Texture? value) -> Texture?
    def texture_rect: () -> Rect
    def texture_rect=: (Rect value) -> Rect
    def point_count: () -> Integer
    def point: (Integer index) -> SF::System::Vector2
    def geometric_center: () -> SF::System::Vector2
    def local_bounds: () -> Rect
    def global_bounds: () -> Rect
    def transform: () -> Array[untyped]
    def inverse_transform: () -> Array[untyped]
    def matrix: () -> Array[untyped]
  end
end
