module SF::Graphics
  class RenderState
    def initialize: () -> void
                 | (Array[Array[Float]] | Array[Float] matrix) -> void

    def transform: () -> Array[untyped]
    def transform=: (Array[Array[Float]] | Array[Float] matrix) -> self
    def matrix: () -> Array[untyped]
    def matrix=: (Array[Array[Float]] | Array[Float] matrix) -> self
    def blend_mode: () -> BlendMode
    def blend_mode=: (BlendMode value) -> BlendMode
    def stencil_mode: () -> StencilMode
    def stencil_mode=: (StencilMode value) -> StencilMode
    def coordinate_type: () -> Symbol
    def coordinate_type=: (Symbol value) -> Symbol
    def texture: () -> (Texture | nil)
    def texture=: (Texture? value) -> Texture?
    def shader: () -> (Shader | nil)
    def shader=: (Shader? value) -> Shader?
  end
end
