module SFML
  class Target
    def initialize: (untyped window) -> void
    def draw: (untyped drawable, untyped state) -> nil
    def view: () -> untyped
    def view=: (untyped value) -> nil
  end
end
