module SF::Graphics
  module Transformable
    def self.new: () -> Transformable::Instance

    def position=: (SF::System::Vector2 value) -> SF::System::Vector2
    def rotation=: (Float value) -> Float
    def scale=: (SF::System::Vector2 value) -> SF::System::Vector2
    def origin=: (SF::System::Vector2 value) -> SF::System::Vector2

    def position: () -> SF::System::Vector2
    def rotation: () -> Float
    def scale: () -> SF::System::Vector2
    def origin: () -> SF::System::Vector2

    def move: (SF::System::Vector2 offset) -> self
    def rotate: (Float angle) -> self
    def scale!: (SF::System::Vector2 factors) -> self

    def transform: () -> Array[Float]
    def matrix: () -> Array[Float]
    def inverse_transform: () -> Array[Float]

    # Internal implementation detail behind Transformable.new.
    class Instance
      include Transformable

      def initialize: () -> void
      def copy: () -> Instance
    end
  end
end
