# frozen_string_literal: true

# Sprites, textures and images -- the graphics path the other examples skip.
# It loads the vendored sprite sheet and animates a cell through
# `Sprite#texture_rect`, builds a texture at runtime from `Image.from_pixels`,
# edits an `Image` pixel by pixel, and renders a live scene into a
# `RenderTexture` that is then drawn back as a sprite. S toggles texture
# smoothing, P toggles repeating, escape quits.
#
# Run from the repository root with a display:
#   bundle exec ruby -Ilib examples/subsystems/graphics_assets/graphics_assets.rb
# (headless: prefix `xvfb-run -a`).

require 'sfml'
include SF::Window
include SF::Graphics
include SF::System

# --- self-contained helpers -------------------------------------------------
ASSETS = File.expand_path('assets', __dir__)

FONT = Font.from_file(File.join(ASSETS, 'LiberationSans-Regular.ttf'))
def text(string, size: 18, position: [12, 8], color: [235, 235, 245, 255])
  label = Text.new(FONT, string, size)
  label.fill_color = color
  label.position = position
  label
end

# Sheet cells in assets/sprites.png (16x16), generated by
# script/generate_example_sprites.rb.
SHEET = Texture.from_file(File.join(ASSETS, 'sprites.png'))
SPRITES = {
  bird_up: [0, 0], bird_mid: [1, 0], bird_down: [2, 0], gem: [5, 0]
}.freeze

def sprite(name, scale: 1)
  column, row = SPRITES.fetch(name)
  result = Sprite.new(SHEET)
  result.texture_rect = [column * 16, row * 16, 16, 16]
  result.scale = [scale, scale] if scale != 1
  result
end

def image(width, height)
  pixels = String.new(encoding: Encoding::BINARY)
  height.times do |y|
    width.times do |x|
      color = yield(x, y)
      color += [255] if color.size == 3
      pixels << color.pack('C4')
    end
  end
  Image.from_pixels([width, height], pixels)
end

def procedural_texture(width, height)
  pixels = String.new(encoding: Encoding::BINARY)
  height.times do |y|
    width.times do |x|
      color = yield(x, y)
      color += [255] if color.size == 3
      pixels << color.pack('C4')
    end
  end
  Texture.from_image(Image.from_pixels([width, height], pixels))
end

WIDTH = 900
HEIGHT = 560

window = Window.new(VideoMode.new(WIDTH, HEIGHT, 32), 'SFML sprites, textures & images')
window.frame_rate = 60

# --- a sprite sheet loaded from disk, animated via texture_rect --------------
BIRD_FRAMES = %i[bird_up bird_mid bird_down bird_mid].freeze
bird = sprite(:bird_down, scale: 4)
bird.position = [60, 70]

gem = sprite(:gem, scale: 3)
gem.origin = [8, 8]
gem.position = [210, 104]

# --- a procedural texture: an Image block handed to Texture.from_image -------
checker = procedural_texture(32, 32) do |x, y|
  ((x / 8) + (y / 8)).even? ? [62, 92, 142, 255] : [92, 132, 192, 255]
end
checker.repeated = true
backdrop = RectangleShape.new([340, 150])
backdrop.position = [520, 40]
backdrop.texture = checker
backdrop.texture_rect = [0, 0, 340, 150]

# --- Image editing -----------------------------------------------------------
gradient = image(16, 16) { |x, y| [x * 16, y * 16, 140, 255] }
gradient.set_pixel(0, 0, Color.new(255, 255, 255, 255))
sample = gradient.pixel(0, 0)
buffer = gradient.save_to_memory('png')
gradient.flip_vertically!

# --- RenderTexture: draw offscreen, then draw the result as a sprite ----------
render_texture = RenderTexture.new([240, 150])
render_texture.smooth = true
offscreen_clock = Clock.new

def render_offscreen(render_texture, time)
  render_texture.clear([18, 22, 34, 255])
  render_texture.active = true
  5.times do |index|
    angle = (time * 40) + (index * 72)
    shape = RectangleShape.new([46, 14])
    shape.origin = [23, 7]
    shape.position = [120, 75]
    shape.rotation = angle
    shape.fill_color = Color.new(90 + (index * 30), 140, 230 - (index * 20), 220)
    render_texture.draw(shape)
  end
  render_texture.display
  render_texture.active = false
end

render_offscreen(render_texture, 0.0)
offscreen = Sprite.new(render_texture.texture)
offscreen.position = [520, 250]

animation = Clock.new
frame_index = 0

while window.open?
  window.poll_events! do |event|
    case event.type
    when 'closed'
      window.close!
    when 'key-pressed'
      key = event.code
      window.close! if key == :escape
      if key == :s
        checker.smooth = !checker.smooth?
      elsif key == :p
        checker.repeated = !checker.repeated?
      end
    end
  end

  if animation.elapsed_time.as_seconds > 0.14
    animation.restart!
    frame_index = (frame_index + 1) % BIRD_FRAMES.length
  end
  column, row = SPRITES.fetch(BIRD_FRAMES[frame_index])
  bird.texture_rect = [column * 16, row * 16, 16, 16]
  gem.rotation += 2

  render_offscreen(render_texture, offscreen_clock.elapsed_time.as_seconds)

  window.clear!([14, 16, 24, 255])
  window.draw(backdrop)
  window.draw(bird)
  window.draw(gem)
  window.draw(offscreen)

  window.draw(text(
                "Sprite#texture_rect animation over a #{SHEET.size.x.to_i}x" \
                "#{SHEET.size.y.to_i} sheet (16x16 cells)\n" \
                'Texture.from_image from Image.from_pixels (32x32 checker) -- ' \
                "smooth? #{checker.smooth?}  repeated? #{checker.repeated?}\n" \
                "Image: size #{gradient.size.x.to_i}x#{gradient.size.y.to_i}  " \
                "pixel(0,0)=#{sample}  save_to_memory(png)=#{buffer ? "#{buffer.size} bytes" : 'nil'}\n" \
                'RenderTexture drawn offscreen, then shown through its #texture',
                size: 15, position: [40, 250]
              ))
  window.draw(text('S smoothing, P repeating, escape quits',
                   size: 14, position: [40, 370]))
  window.display!

end
