module SF::Audio
  class SoundBufferRecorder < SoundRecorder
    def initialize: () -> void
    def self.record!: (?sample_rate: Integer, ?device: String?, ?channel_count: Integer?) ?{ (SoundBufferRecorder) -> untyped } -> SoundBuffer

    def start: (Integer sample_rate) -> bool
    def stop: () -> self
    def sample_rate: () -> Integer
    def buffer: () -> SoundBuffer
    def device: () -> String
    def device=: (String value) -> bool
    def channel_count: () -> Integer
    def channel_count=: (Integer value) -> Integer
  end
end
