module SF::Network
  class TcpListener
    def initialize: () -> void
    def self.any_port: () -> Integer

    def blocking?: () -> bool
    def blocking=: (bool value) -> bool
    def local_port: () -> Integer
    def listen: (Integer port, ?IpAddress address) -> Symbol
    def close: () -> self
    def accept: () -> [TcpSocket?, Symbol]
  end
end
