module SFML
  class Clock
    def initialize: () -> void
    def self.measure: () { () -> untyped } -> Time

    def elapsed_time: () -> Time
    def restart!: () -> Time
    def reset!: () -> Time
    def running?: () -> bool
    def start!: () -> self
    def stop!: () -> self
    def copy: () -> Clock
  end
end
