module SFML
  class Vector2
    include Enumerable[Float]

    def initialize: () -> void
                 | (Float x, Float y) -> void
                 | (Array[Float] xy) -> void
                 | (Vector2 other) -> void
    def self.[]: (*untyped args) -> Vector2

    def x: () -> Float
    def x=: (Float value) -> Float
    def y: () -> Float
    def y=: (Float value) -> Float
    def to_a: () -> [Float, Float]
    def to_ary: () -> [Float, Float]
    def each: () { (Float) -> void } -> self
    def []: (Integer index) -> Float
    def size: () -> Integer
    def length: () -> Integer
    def ==: (untyped other) -> bool
    def +: (Vector2 | Array[Float] other) -> Vector2
    def -: (Vector2 | Array[Float] other) -> Vector2
    def *: (Float scalar) -> Vector2
    def to_s: () -> String
  end
end
