module SFML
  module Sensor
    def self.available?: (Symbol | Integer type) -> bool
    def self.set_enabled: (Symbol | Integer type, bool value) -> bool
    def self.enabled=: (Symbol | Integer type, bool value) -> bool
    def self.value: (Symbol | Integer type) -> Vector3
  end
end
