module SFML
  module Touch
    def self.down?: (Integer finger) -> bool
    def self.position: (Integer finger, ?WindowBase? window, ?relative_to: WindowBase?) -> Vector2
    private def self.position_without_relative_to: (Integer finger, ?WindowBase? window) -> Vector2
  end
end
