# frozen_string_literal: true

# Shared helpers for the examples that need an asset or a HUD. Loads the
# bundled font and WAVs once, and exposes the SFML_EXAMPLE_FRAMES hook that lets
# every interactive example run headlessly for a fixed number of frames:
#
#   SFML_EXAMPLE_FRAMES=120 xvfb-run -a bundle exec ruby -Ilib examples/subsystems/mouse.rb
#
# The assets live in examples/assets/ and are shipped with the gem (see the
# `examples/**/*.{ttf,wav,txt}` glob in sfml3-rb.gemspec).

require 'sfml'

module ExampleSupport
  ASSET_DIR = File.expand_path('assets', __dir__)

  module_function

  def asset(name)
    File.join(ASSET_DIR, name)
  end

  # Runs until the user closes the window, unless SFML_EXAMPLE_FRAMES is set, in
  # which case it reports true after that many frames.
  def auto_close?(frame)
    limit = ENV.fetch('SFML_EXAMPLE_FRAMES', nil)
    limit = Integer(limit, exception: false) if limit
    !limit.nil? && frame >= limit
  end

  # The bundled Liberation Sans (SIL OFL 1.1, see assets/LICENSE-LiberationSans.txt).
  def font
    @font ||= SFML::Font.from_file(asset('LiberationSans-Regular.ttf'))
  end

  def text(string, size: 18, position: [12, 8], color: [235, 235, 245, 255])
    label = SFML::Text.new(font, string, size)
    label.fill_color = color
    label.position = position
    label
  end

  # A Sound for examples/assets/<name>.wav, ready to `play`.
  def sound(name, volume: 60)
    buffer = SFML::SoundBuffer.from_file(asset("#{name}.wav"))
    SFML::Sound.new(buffer).tap { |sound| sound.volume = volume }
  end

  # A VertexArray of one or more disjoint two-point segments, drawn with
  # window.draw. Handy for crosshairs, grids and simple debug overlays.
  def line(points, color)
    array = SFML::VertexArray.new
    points.each { |pair| array.append(SFML::Vertex.new(pair, color)) }
    array.primitive = :lines
    array
  end

  # --- textures, images and the vendored sprite sheet ------------------------

  SHEET_NAME = 'sprites.png'
  SHEET_CELL = 16
  SHEET_COLUMNS = 8

  # Cell coordinates in examples/assets/sprites.png, generated by
  # script/generate_example_sprites.rb.
  SPRITES = {
    bird_up: [0, 0], bird_mid: [1, 0], bird_down: [2, 0],
    pipe: [3, 0], platform: [4, 0], gem: [5, 0], car: [6, 0], doodler: [7, 0],
    tetro_i: [0, 1], tetro_o: [1, 1], tetro_t: [2, 1], tetro_s: [3, 1],
    tetro_z: [4, 1], tetro_j: [5, 1], tetro_l: [6, 1], spring: [7, 1],
    coin: [0, 2], brick_red: [1, 2], brick_blue: [2, 2], grass: [3, 2],
    enemy: [4, 2], star: [5, 2], block: [6, 2], arrow: [7, 2]
  }.freeze

  def textures
    @textures ||= {}
  end

  # A cached Texture for a file under examples/assets/.
  def texture(name)
    textures[name] ||= SFML::Texture.from_file(asset(name))
  end

  def sheet
    texture(SHEET_NAME)
  end

  # An Image built from a block returning [r, g, b, a] (alpha optional) for
  # every pixel. Builds the raw buffer once and hands it to Image.from_pixels.
  def image(width, height)
    pixels = String.new(encoding: Encoding::BINARY)
    height.times do |y|
      width.times do |x|
        color = yield(x, y)
        color += [255] if color.size == 3
        pixels << color.pack('C4')
      end
    end
    SFML::Image.from_pixels([width, height], pixels)
  end

  # A Texture generated at runtime instead of loaded from disk.
  def procedural_texture(width, height, &)
    SFML::Texture.from_image(image(width, height, &))
  end

  # A Sprite showing one cell of the vendored sheet, scaled by an integer.
  def sprite(name, scale: 1)
    column, row = SPRITES.fetch(name)
    result = SFML::Sprite.new(sheet)
    result.texture_rect = [column * SHEET_CELL, row * SHEET_CELL, SHEET_CELL, SHEET_CELL]
    result.scale = [scale, scale] if scale != 1
    result
  end
end
