name: Check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v2
        with:
          ruby-version: 3.2
          gems: |
            bundler
            rubocop

      - name: Install gems
        run: bundle install --jobs 4

      - name: Run RuboCop
        run: bundle exec rubocop