name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          gems: |
            bundler

      - name: Install gems
        run: bundle install --jobs 4

      - name: Build gem
        run: gem build sfml3-rb.gemspec

      - name: Publish gem
        run: |
          gem push sfml3-rb-*.gem \
            -k rubygems \
            --host https://rubygems.org \
            ENV["RUBYGEMS_API_KEY"]
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}