name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install CSFML and build deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libcsfml-dev build-essential libgl1-mesa-dev libx11-dev libxrandr-dev libxcursor-dev libudev-dev libopenal-dev

      - uses: ruby/setup-ruby@v2
        with:
          ruby-version: 3.2
          gems: |
            bundler
            rake
            minitest
            rubocop
            rice

      - name: Install gems
        run: bundle install --jobs 4

      - name: Run tests
        run: bundle exec rake test